BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SALES_RECORD CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE ORDER_ITEM CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE ORDERS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE STOCK_MOVEMENT CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE WAREHOUSE CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE SUPPLIER CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE PRODUCT CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PRODUCT (
    product_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR2(100) NOT NULL,
    category        VARCHAR2(50),
    price           NUMBER(10, 2), 
    min_stock_level NUMBER DEFAULT 0
);

CREATE TABLE SUPPLIER (
    supplier_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR2(100) NOT NULL,
    phone           VARCHAR2(20),
    address         VARCHAR2(200),
    email           VARCHAR2(100)
);

CREATE TABLE WAREHOUSE (
    warehouse_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR2(100),
    location        VARCHAR2(200),
    supplier_id     NUMBER,
    FOREIGN KEY (supplier_id) REFERENCES SUPPLIER(supplier_id)
);

CREATE TABLE ORDERS (
    order_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id     NUMBER,
    order_date      DATE DEFAULT SYSDATE,
    status          VARCHAR2(20) CHECK (status IN ('Onay Bekliyor', 'Teslim Edildi', 'İptal Edildi')),
    FOREIGN KEY (supplier_id) REFERENCES SUPPLIER(supplier_id)
);

CREATE TABLE ORDER_ITEM (
    item_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        NUMBER,
    product_id      NUMBER,
    quantity        NUMBER,
    unit_price      NUMBER(10, 2),
    FOREIGN KEY (order_id) REFERENCES ORDERS(order_id),
    FOREIGN KEY (product_id) REFERENCES PRODUCT(product_id)
);

CREATE TABLE STOCK_MOVEMENT (
    movement_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id      NUMBER,
    warehouse_id    NUMBER,
    movement_type   VARCHAR2(10) CHECK (movement_type IN ('IN', 'OUT')),
    quantity        NUMBER,
    movement_date   DATE DEFAULT SYSDATE,
    FOREIGN KEY (product_id) REFERENCES PRODUCT(product_id),
    FOREIGN KEY (warehouse_id) REFERENCES WAREHOUSE(warehouse_id)
);

CREATE TABLE SALES_RECORD (
    sale_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id      NUMBER,
    customer_name   VARCHAR2(100),
    sale_date       DATE DEFAULT SYSDATE,
    quantity        NUMBER,
    total_price     NUMBER(10, 2),
    FOREIGN KEY (product_id) REFERENCES PRODUCT(product_id)
);

-- Örnek Veri Girişi 
INSERT INTO PRODUCT (name, category, price, min_stock_level) VALUES ('Laptop', 'Elektronik', 15000, 10);
INSERT INTO PRODUCT (name, category, price, min_stock_level) VALUES ('Mouse', 'Aksesuar', 250, 50);
INSERT INTO PRODUCT (name, category, price, min_stock_level) VALUES ('Klavye', 'Aksesuar', 450, 20);

INSERT INTO SUPPLIER (name, phone, email) VALUES ('Tekno Toptan', '05551234567', 'info@tekno.com');
INSERT INTO SUPPLIER (name, phone, email) VALUES ('Global Lojistik', '02129998877', 'info@global.com');
INSERT INTO SUPPLIER (name, phone, email) VALUES ('Hizli Tedarik', '05321112233', 'siparis@hizli.com');

INSERT INTO WAREHOUSE (name, location, supplier_id) VALUES ('Merkez Depo', 'Ankara Incek', 1);
INSERT INTO WAREHOUSE (name, location, supplier_id) VALUES ('Duru Dagitim', 'Istanbul Kadikoy', 2);
INSERT INTO WAREHOUSE (name, location, supplier_id) VALUES ('Afyon Depo', 'Afyon Merkez', 3);

INSERT INTO SALES_RECORD (product_id, customer_name, quantity, total_price) VALUES (1, 'Beyza Soykasap', 1, 15000);
INSERT INTO SALES_RECORD (product_id, customer_name, quantity, total_price) VALUES (2, 'Beyza Nur Erol', 2, 500);
INSERT INTO SALES_RECORD (product_id, customer_name, quantity, total_price) VALUES (3, 'Delfin Ceylan', 5, 2250);

INSERT INTO STOCK_MOVEMENT (product_id, warehouse_id, movement_type, quantity) VALUES (1, 1, 'IN', 100);
INSERT INTO STOCK_MOVEMENT (product_id, warehouse_id, movement_type, quantity) VALUES (2, 2, 'IN', 500);
INSERT INTO STOCK_MOVEMENT (product_id, warehouse_id, movement_type, quantity) VALUES (1, 1, 'OUT', 10);

INSERT INTO ORDERS (supplier_id, status) VALUES (1, 'Teslim Edildi');
INSERT INTO ORDERS (supplier_id, status) VALUES (2, 'Onay Bekliyor');
INSERT INTO ORDERS (supplier_id, status) VALUES (3, 'Teslim Edildi');

INSERT INTO ORDER_ITEM (order_id, product_id, quantity, unit_price) VALUES (1, 1, 10, 14000);
INSERT INTO ORDER_ITEM (order_id, product_id, quantity, unit_price) VALUES (2, 2, 100, 200);
INSERT INTO ORDER_ITEM (order_id, product_id, quantity, unit_price) VALUES (3, 3, 50, 400);

COMMIT;